unit Model.Entregas;

interface

  type
    TEntregas = class
    private
      var
      FNN: String;
      FDistribuidor: Integer;
      FEntregador: Integer;
      FCliente: Integer;
      FNF: String;
      FConsumidor: String;
      FEndereco: String;
      FComplemento: String;
      FBairro: String;
      FCidade: String;
      FCEP: String;
      FTelefone: String;
      FExpedicao: TDate;
      FPrevisao: TDate;
      FVolumes: Integer;
      FAtribuicao: TDateTime;
      FBaixa: TDate;
      FBaixado: String;
      FPagamento: TDate;
      FPago: String;
      FFechado: String;
      FStatus: Integer;
      FEntrega: TDate;
      FPesoReal: Double;
      FPesoFranquia: Double;
      FVerbaFranquia: Double;
      FAdvalorem: Double;
      FPagoFranquia: Double;
      FVerbaEntregador: Double;
      FExtrato: String;
      FAtraso: Integer;
      FVolumesExtra: Double;
      FValorVolumes: Double;
      FPesoCobrado: Double;
      FTipoPeso: String;
      FRecebimento: TDate;
      FRecebido: String;
      FCTRC: Integer;
      FManifesto: Integer;
      FRastreio: String;
      FLote: Integer;
      FRetorno: String;
      FCredito: TDate;
      FCreditado: String;
      FContainer: String;
      FValorProduto: Double;
      FAltura: Integer;
      FLargura: Integer;
      FComprimento: Integer;
      FCodigoFeedback: Integer;
      FDataFeedback: TDateTime;
      FConferido: Integer;
      FPedido: String;
      FCodCliente: Integer;
    public
      property NN: String               read  FNN               write   FNN;
      property Distribuidor: Integer    read  FDistribuidor     write   FDistribuidor;
      property Entregador: Integer      read  FEntregador       write   FEntregador;
      property Cliente: Integer         read  FCliente          write   FCliente;
      property NF: String               read  FNF               write   FNF;
      property Consumidor: String       read  FConsumidor       write   FConsumidor;
      property Endereco: String         read  FEndereco         write   FEndereco;
      property Complemento: String      read  FComplemento      write   FComplemento;
      property Bairro: String           read  FBairro           write   FBairro;
      property Cidade: String           read  FCidade           write   FCidade;
      property CEP: String              read  FCEP              write   FCEP;
      property Telefone: String         read  FTelefone         write   FTelefone;
      property Expedicao: TDate         read  FExpedicao        write   FExpedicao;
      property Previsao: TDate          read  FPrevisao         write   FPrevisao;
      property Volumes: Integer         read  FVolumes          write   FVolumes;
      property Atribuicao: TDateTime    read  FAtribuicao       write   FAtribuicao;
      property Baixa: TDate             read  FBaixa            write   FBaixa;
      property Baixado: String          read  FBaixado          write   FBaixado;
      property Pagamento: TDate         read  FPagamento        write   FPagamento;
      property Pago: String             read  FPago             write   FPago;
      property Fechado: String          read  FFechado          write   FFechado;
      property Status: Integer          read  FStatus           write   FStatus;
      property Entrega: TDate           read  FEntrega          write   FEntrega;
      property PesoReal: Double         read  FPesoReal         write   FPesoReal;
      property PesoFranquia: Double     read  FPesoFranquia     write   FPesoFranquia;
      property VerbaFranquia: Double    read  FVerbaFranquia    write   FVerbaFranquia;
      property Advalorem: Double        read  FAdvalorem        write   FAdvalorem;
      property PagoFranquia: Double     read  FPagoFranquia     write   FPagoFranquia;
      property VerbaEntregador: Double  read  FVerbaEntregador  write   FVerbaEntregador;
      property Extrato: String          read  FExtrato          write   FExtrato;
      property Atraso: Integer          read  FAtraso           write   FAtraso;
      property VolumesExtra: Double     read  FVolumesExtra     write   FVolumesExtra;
      property ValorVolumes: Double     read  FValorVolumes     write   FValorVolumes;
      property PesoCobrado: Double      read  FPesoCobrado      write   FPesoCobrado;
      property TipoPeso: String         read  FTipoPeso         write   FTipoPeso;
      property Recebimento: TDate       read  FRecebimento      write   FRecebimento;
      property Recebido: String         read  FRecebido         write   FRecebido;
      property CTRC: Integer            read  FCTRC             write   FCTRC;
      property Manifesto: Integer       read  FManifesto        write   FManifesto;
      property Rastreio: String         read  FRastreio         write   FRastreio;
      property Lote: Integer            read  FLote             write   FLote;
      property Retorno: String          read  FRetorno          write   FRetorno;
      property Credito: TDate           read  FCredito          write   FCredito;
      property Creditado: String        read  FCreditado        write   FCreditado;
      property Container: String        read  FContainer        write   FContainer;
      property ValorProduto: Double     read  FValorProduto     write   FValorProduto;
      property Altura: Integer          read  FAltura           write   FAltura ;
      property Largura: Integer         read  FLargura          write   FLargura;
      property Comprimento: Integer     read  FComprimento      write   FComprimento;
      property CodigoFeedback: Integer  read  FCodigoFeedback   write   FCodigoFeedback;
      property DataFeedback: TDateTime  read  FDataFeedback     write   FDataFeedback;
      property Conferido: Integer       read  FConferido        write   FConferido;
      property Pedido: String           read  FPedido           write   FPedido;
      property CodCliente: Integer      read  FCodCliente       write   FCodCliente;
      constructor Create; overload;
      constructor Create(pFNN: String; pFDistribuidor: Integer; pFEntregador: Integer; pFCliente: Integer; pFNF: String;
                         pFConsumidor: String; pFEndereco: String; pFComplemento: String; pFBairro: String; pFCidade: String;
                         pFCEP: String; pFTelefone: String; pFExpedicao: TDate; pFPrevisao: TDate; pFVolumes: Integer;
                         pFAtribuicao: TDateTime; pFBaixa: TDate; pFBaixado: String; pFPagamento: TDate; pFPago: String;
                         pFFechado: String; pFStatus: Integer; pFEntrega: TDate; pFPesoReal: Double; pFPesoFranquia: Double;
                         pFVerbaFranquia: Double; pFAdvalorem: Double; pFPagoFranquia: Double; pFVerbaEntregador: Double;
                         pFExtrato: String; pFAtraso: Integer; pFVolumesExtra: Double; pFValorVolumes: Double;
                         pFPesoCobrado: Double; pFTipoPeso: String; pFRecebimento: TDate; pFRecebido: String; pFCTRC: Integer;
                         pFManifesto: Integer; pFRastreio: String; pFLote: Integer; pFRetorno: String; pFCredito: TDate;
                         pFCreditado: String; pFContainer: String; pFValorProduto: Double; pFAltura: Integer; pFLargura: Integer;
                         pFComprimento: Integer; pFCodigoFeedback: Integer; pFDataFeedback: TDateTime;
                         pFConferido: Integer; pFPedido: String; pFCodCliente: Integer); overload;
    end;

implementation

constructor TEntregas.Create;
begin
  inherited Create;
end;

constructor TEntregas.Create(pFNN: String; pFDistribuidor: Integer; pFEntregador: Integer; pFCliente: Integer; pFNF: String;
                         pFConsumidor: String; pFEndereco: String; pFComplemento: String; pFBairro: String; pFCidade: String;
                         pFCEP: String; pFTelefone: String; pFExpedicao: TDate; pFPrevisao: TDate; pFVolumes: Integer;
                         pFAtribuicao: TDateTime; pFBaixa: TDate; pFBaixado: String; pFPagamento: TDate; pFPago: String;
                         pFFechado: String; pFStatus: Integer; pFEntrega: TDate; pFPesoReal: Double; pFPesoFranquia: Double;
                         pFVerbaFranquia: Double; pFAdvalorem: Double; pFPagoFranquia: Double; pFVerbaEntregador: Double;
                         pFExtrato: String; pFAtraso: Integer; pFVolumesExtra: Double; pFValorVolumes: Double;
                         pFPesoCobrado: Double; pFTipoPeso: String; pFRecebimento: TDate; pFRecebido: String; pFCTRC: Integer;
                         pFManifesto: Integer; pFRastreio: String; pFLote: Integer; pFRetorno: String; pFCredito: TDate;
                         pFCreditado: String; pFContainer: String; pFValorProduto: Double; pFAltura: Integer; pFLargura: Integer;
                         pFComprimento: Integer; pFCodigoFeedback: Integer; pFDataFeedback: TDateTime;
                         pFConferido: Integer; pFPedido: String; pFCodCliente: Integer);
begin
  FNN := pFNN;
  FDistribuidor := pFDistribuidor;
  FEntregador := pFEntregador;
  FCliente := pFCliente;
  FNF := pFNF;
  FConsumidor := pFConsumidor;
  FEndereco := pFEndereco;
  FComplemento := pFComplemento;
  FBairro := pFBairro;
  FCidade := pFCidade;
  FCEP := pFCEP;
  FTelefone := pFTelefone;
  FExpedicao := pFExpedicao;
  FPrevisao := pFPrevisao;
  FVolumes := pFVolumes;
  FAtribuicao := pFAtribuicao;
  FBaixa := pFBaixa;
  FBaixado := pFBaixado;
  FPagamento := pFPagamento;
  FPago := pFPago;
  FFechado := pFFechado;
  FStatus := pFStatus;
  FEntrega := pFEntrega;
  FPesoReal := pFPesoReal;
  FPesoFranquia := pFPesoFranquia;
  FVerbaFranquia := pFVerbaFranquia;
  FAdvalorem := pFAdvalorem;
  FPagoFranquia := pFPagoFranquia;
  FVerbaEntregador := pFVerbaEntregador;
  FExtrato := pFExtrato;
  FAtraso := pFAtraso;
  FVolumesExtra := pFVolumesExtra;
  FValorVolumes := pFValorVolumes;
  FPesoCobrado := pFPesoCobrado;
  FTipoPeso := pFTipoPeso;
  FRecebimento := pFRecebimento;
  FRecebido := pFRecebido;
  FCTRC := pFCTRC;
  FManifesto := pFManifesto;
  FRastreio := pFRastreio;
  FLote := pFLote;
  FRetorno := pFRetorno;
  FCredito := pFCredito;
  FCreditado := pFCreditado;
  FContainer := pFContainer;
  FValorProduto := pFValorProduto;
  FAltura := pFAltura;
  FLargura := pFLargura;
  FComprimento := pFComprimento;
  FCodigoFeedback := pFCodigoFeedback;
  FDataFeedback := pFDataFeedback;
  FConferido := pFConferido;
  FPedido := pFPedido;
  FCodCliente :=  pFCodCliente;
end;

end.
