unit udm;

interface

uses
  Windows, SysUtils, Classes, DB, SqlExpr, FMTBcd, Provider, DBClient,
  cxHint, ImgList, Controls, cxGraphics, Dialogs, cxStyles, cxClasses,
  cxGridTableView, cxLookAndFeels, dxSkinsCore, dxSkinBlack, dxSkinBlue,
  dxSkinBlueprint, dxSkinCaramel, dxSkinCoffee, dxSkinDarkRoom, dxSkinDarkSide,
  dxSkinDevExpressDarkStyle, dxSkinDevExpressStyle, dxSkinFoggy,
  dxSkinGlassOceans, dxSkinHighContrast, dxSkiniMaginary, dxSkinLilian,
  dxSkinLiquidSky, dxSkinLondonLiquidSky, dxSkinMcSkin, dxSkinMoneyTwins,
  dxSkinOffice2007Black, dxSkinOffice2007Blue, dxSkinOffice2007Green,
  dxSkinOffice2007Pink, dxSkinOffice2007Silver, dxSkinOffice2010Black,
  dxSkinOffice2010Blue, dxSkinOffice2010Silver, dxSkinPumpkin, dxSkinSeven,
  dxSkinSevenClassic, dxSkinSharp, dxSkinSharpPlus, dxSkinSilver,
  dxSkinSpringTime, dxSkinStardust, dxSkinSummer2008, dxSkinTheAsphaltWorld,
  dxSkinsDefaultPainters, dxSkinValentine, dxSkinVS2010, dxSkinWhiteprint,
  dxSkinXmas2008Blue, dxScreenTip, dxSkinsForm, dxCustomHint, dxmdaset,
  ZAbstractRODataset, ZAbstractDataset, ZDataset, ZAbstractConnection,
  ZConnection, VCL.Forms, VCL.ActnList,
  dxSkinMetropolis, dxSkinMetropolisDark, dxSkinOffice2013DarkGray,
  dxSkinOffice2013LightGray, dxSkinOffice2013White, dxLayoutLookAndFeels, FireDAC.Stan.Intf, FireDAC.Stan.Option,
  FireDAC.Stan.Error, FireDAC.UI.Intf, FireDAC.Phys.Intf, FireDAC.Stan.Def, FireDAC.Stan.Pool, FireDAC.Stan.Async, FireDAC.Phys,
  FireDAC.Phys.MySQL, FireDAC.VCLUI.Wait, FireDAC.Comp.UI, FireDAC.Comp.Client, FireDAC.Stan.Param, FireDAC.DatS, FireDAC.DApt.Intf,
  FireDAC.DApt, FireDAC.Comp.DataSet, cxLocalization, clUtil, FireDAC.Phys.MySQLDef, FireDAC.VCLUI.Async,
  FireDAC.Comp.BatchMove.Text, FireDAC.Comp.BatchMove, FireDAC.Comp.BatchMove.DataSet, dxSkinOffice2016Colorful,
  dxSkinOffice2016Dark, dxSkinVisualStudio2013Blue, dxSkinVisualStudio2013Dark, dxSkinVisualStudio2013Light, System.ImageList,
  frxExportCSV, frxExportText, frxExportImage, frxExportRTF, frxExportHTML, frxClass, frxExportPDF, frxDBSet;

type
  Tdm = class(TDataModule)
    ZConn: TZConnection;
    qryCRUD: TZQuery;
    qryGetObject: TZQuery;
    ttba: TdxMemData;
    ttbaDES_SERVIDOR_SMTP: TStringField;
    ttbaDES_EMAIL_REMETENTE: TStringField;
    ttbaDES_USERNAME: TStringField;
    ttbaDES_SENHA: TStringField;
    tbParLocal: TdxMemData;
    tbParLocalDOM_ESTILO: TIntegerField;
    ttbaDOM_USUARIO_LOGADO: TBooleanField;
    ttbaDOM_HISTORICO: TBooleanField;
    ttbaDOM_AUTH_SMTP: TStringField;
    cxImageList1: TcxImageList;
    cxImageList2: TcxImageList;
    qryGeral: TZQuery;
    qryPesquisa: TZQuery;
    qryCalculo: TZQuery;
    tbApoio: TdxMemData;
    ttbaNOM_SKIN: TStringField;
    qryGrid: TZQuery;
    tbExtrato: TdxMemData;
    tbAtribuicoes: TdxMemData;
    tbAtribuicoesNUM_NOSSONUMERO: TStringField;
    tbAtribuicoesNOM_CONSUMIDOR: TStringField;
    tbAtribuicoesDES_ENDERECO: TStringField;
    tbAtribuicoesDES_COMPLEMENTO: TStringField;
    tbAtribuicoesDES_BAIRRO: TStringField;
    tbAtribuicoesNOM_CIDADE: TStringField;
    tbAtribuicoesNUM_CEP: TStringField;
    tbAtribuicoesQTD_VOLUMES: TIntegerField;
    tbAtribuicoesQTD_PESO_REAL: TFloatField;
    tbAtribuicoesCOD_AGENTE: TIntegerField;
    tbAtribuicoesCOD_ENTREGADOR: TIntegerField;
    tbAtribuicoesDAT_ATRIBUICAO: TDateField;
    tbRecepcao: TdxMemData;
    tbRecepcaoNUM_MANIFESTO: TIntegerField;
    tbRecepcaoNUM_CTRC: TIntegerField;
    tbRecepcaoNUM_NOSSONUMERO: TStringField;
    tbRecepcaoNOM_CONSUMIDOR: TStringField;
    tbRecepcaoDES_ENDERECO: TStringField;
    tbRecepcaoDES_COMPLEMENTO: TStringField;
    tbRecepcaoDES_BAIRRO: TStringField;
    tbRecepcaoNOM_CIDADE: TStringField;
    tbRecepcaoQTD_VOLUMES: TIntegerField;
    tbRecepcaoQTD_PESO_REAL: TFloatField;
    tbRecepcaoNUM_CEP: TStringField;
    tbRetorno: TdxMemData;
    tbRetornoNUM_NOSSONUMERO: TStringField;
    tbRetornoNOM_CONSUMIDOR: TStringField;
    tbRetornoDES_ENDERECO: TStringField;
    tbRetornoDES_BAIRRO: TStringField;
    tbRetornoNOM_CIDADE: TStringField;
    tbRetornoNUM_CEP: TStringField;
    tbRetornoQTD_VOLUMES: TIntegerField;
    tbRetornoQTD_PESO_REAL: TFloatField;
    tbRetornoCOD_AGENTE: TIntegerField;
    tbRetornoCOD_ENTREGADOR: TIntegerField;
    tbRetornoDES_RASTREIO: TMemoField;
    tbRetornoDES_RETORNO: TStringField;
    tbRetornoDAT_BAIXA: TDateField;
    tbRetornoNOM_AGENTE: TStringField;
    tbRetornoNOM_ENTREGADOR: TStringField;
    qryFields: TZQuery;
    tbLancamentos: TdxMemData;
    tbLancamentosCOD_LANCAMENTO: TIntegerField;
    tbLancamentosDES_LANCAMENTO: TStringField;
    tbLancamentosDAT_LANCAMENTO: TDateField;
    tbLancamentosCOD_ENTREGADOR: TIntegerField;
    tbLancamentosNOM_ENTREGADOR: TStringField;
    tbLancamentosDES_TIPO: TStringField;
    tbLancamentosVAL_LANCAMENTO: TFloatField;
    tbLancamentosDOM_DESCONTO: TStringField;
    tbLancamentosDAT_DESCONTO: TDateField;
    tbLancamentosNUM_EXTRATO: TStringField;
    tbLancamentosVAL_DEBITO: TFloatField;
    tbRestricoesCOD_RESTRICAO: TIntegerField;
    tbRestricoesNOM_AGENTE: TStringField;
    tbRestricoesNOM_ENTREGADOR: TStringField;
    tbRestricoesVAL_RESTRICAO: TFloatField;
    tbRestricoesVAL_PAGO: TFloatField;
    tbRestricoesVAL_DEBITAR: TFloatField;
    tbRestricoes: TdxMemData;
    tbUsuariosAgentes: TdxMemData;
    tbUsuariosAgentesCOD_USUARIO: TIntegerField;
    tbUsuariosAgentesCOD_AGENTE: TIntegerField;
    tbUsuariosAgentesNOM_AGENTE: TStringField;
    tbVeiculos: TdxMemData;
    tbVeiculosDES_PLACA: TStringField;
    tbVeiculosNUM_CNPJ: TStringField;
    tbVeiculosNOM_PROPRIETARIO: TStringField;
    tbVeiculosDES_RAZAO_SOCIAL: TStringField;
    tbVeiculosDES_MODELO: TStringField;
    tbVeiculosDES_TIPO: TStringField;
    tbVeiculosNUM_CHASSIS: TStringField;
    tbVeiculosDES_ANO: TStringField;
    tbVeiculosNUM_RENAVAN: TStringField;
    tbVeiculosANO_EXERCICIO_CLRV: TStringField;
    tbVeiculosCOD_VEICULO: TIntegerField;
    tbPrevia: TdxMemData;
    tbPreviaCOD_ENTREGADOR: TIntegerField;
    tbPreviaNOM_FANTASIA: TStringField;
    tbProcedimentos: TdxMemData;
    tbProcedimentosSEQ_DETALHE: TIntegerField;
    tbProcedimentosDES_TRANSPORTE: TStringField;
    tbProcedimentosHOR_CHEGADA: TTimeField;
    tbProcedimentosHOR_SAIDA: TTimeField;
    tbProcedimentosDES_OBSERVACOES: TMemoField;
    tbPesquisaEntregador: TdxMemData;
    tbPesquisaEntregadorCOD_AGENTE: TIntegerField;
    tbPesquisaEntregadorNOM_AGENTE: TStringField;
    tbPesquisaEntregadorCOD_ENTREGADOR: TIntegerField;
    tbPesquisaEntregadorNOM_ENTREGADOR: TStringField;
    tbPesquisaEntregadorDAT_GV: TDateField;
    tbPesquisaEntregadorDAT_CNH: TDateField;
    tbPesquisaEntregadorCOD_CADASTRO: TIntegerField;
    tbPesquisaEntregadorCOD_STATUS: TIntegerField;
    tbProcedimentosHOR_INICIO_CARGA: TTimeField;
    tbProcedimentosHOR_TERMINO_CARGA: TTimeField;
    tbPesquisaEntregadorDES_ENTREGADOR: TStringField;
    tbPesquisaEntregadorNUM_CPF: TStringField;
    tbDevolucao: TdxMemData;
    tbDevolucaoCOD_BASE: TIntegerField;
    tbDevolucaoDES_BASE: TStringField;
    tbDevolucaoDAT_EXPEDICAO: TDateField;
    tbDevolucaoNUM_NOSSONUMERO: TStringField;
    tbDevolucaoCOD_STATUS: TIntegerField;
    tbDevolucaoNUM_VOLUME: TIntegerField;
    tbDevolucaoDES_CEP: TStringField;
    tbDevolucaoDOM_MARCA: TStringField;
    tbImportacaoExtravio: TdxMemData;
    tbImportacaoExtravioNUM_NOSSONUMERO: TStringField;
    tbImportacaoExtravioDES_EXTRAVIO: TStringField;
    tbImportacaoExtravioDAT_EXTRAVIO: TDateField;
    tbImportacaoExtravioCOD_ENTREGADOR: TIntegerField;
    tbImportacaoExtravioNOM_ENTREGADOR: TStringField;
    tbImportacaoExtravioVAL_PRODUTO: TFloatField;
    tbImportacaoExtravioVAL_MULTA: TFloatField;
    tbImportacaoExtravioVAL_VERBA: TFloatField;
    tbImportacaoExtravioDES_RESTRICAO: TStringField;
    tbPreviaQTD_ENTREGAS_2: TIntegerField;
    tbPreviaQTD_ENTREGAS_3: TIntegerField;
    tbPreviaQTD_ENTREGAS_4: TIntegerField;
    tbPreviaQTD_ENTREGAS_5: TIntegerField;
    tbPreviaQTD_ENTREGAS_6: TIntegerField;
    tbPreviaQTD_ENTREGAS_7: TIntegerField;
    tbPreviaQTD_ENTREGAS_8: TIntegerField;
    tbPreviaQTD_ENTREGAS_9: TIntegerField;
    tbPreviaQTD_ENTREGAS_10: TIntegerField;
    tbPreviaQTD_ENTREGAS_11: TIntegerField;
    tbPreviaQTD_ENTREGAS_12: TIntegerField;
    tbPreviaQTD_ENTREGAS_13: TIntegerField;
    tbPreviaQTD_ENTREGAS_14: TIntegerField;
    tbPreviaQTD_ENTREGAS_15: TIntegerField;
    tbPreviaQTD_ENTREGAS_16: TIntegerField;
    tbPreviaQTD_TOTAL: TIntegerField;
    tbPreviaQTD_ENTREGAS_1: TIntegerField;
    tbPreviaDES_AGENTE: TStringField;
    tbVeiculosUF_PLACA: TStringField;
    tbRestricoesCOD_AGENTE: TIntegerField;
    tbRestricoesCOD_ENTREGADOR: TIntegerField;
    tbRestricoesDOM_RESTRICAO: TStringField;
    tbExtravios: TdxMemData;
    tbAcareacoes: TdxMemData;
    tbAssinantes: TdxMemData;
    tbImportacaoEtiquetas: TdxMemData;
    dsImportaEtiquetas: TDataSource;
    tbProdutos: TdxMemData;
    tbEstados: TdxMemData;
    tbTipoAssinatura: TdxMemData;
    tbEstadosUF_ESTADO: TWideStringField;
    tbEstadosNOM_ESTADO: TWideStringField;
    tbEtiquetas: TdxMemData;
    tbProdutosCOD_PRODUTO: TWideStringField;
    tbProdutosDES_PRODUTO: TWideStringField;
    ZConn1: TZConnection;
    qryCRUD1: TZQuery;
    qryGetObject1: TZQuery;
    qryGeral1: TZQuery;
    qryPesquisa1: TZQuery;
    qryCalculo1: TZQuery;
    qryGrid1: TZQuery;
    qryFields1: TZQuery;
    tbTipoAssinaturaCOD_TIPO_ASSINATURA: TWideStringField;
    tbTipoAssinaturaDES_TIPO_ASSINATURA: TWideStringField;
    tbImportacaoEtiquetasID_ASSINANTE: TIntegerField;
    tbImportacaoEtiquetasCOD_ASSINANTE: TWideStringField;
    tbImportacaoEtiquetasCOD_PRODUTO: TWideStringField;
    tbImportacaoEtiquetasCOD_TIPO_ASSINATURA: TWideStringField;
    tbImportacaoEtiquetasNUM_ROTEIRO: TIntegerField;
    tbImportacaoEtiquetasNUM_EDICAO: TWideStringField;
    tbImportacaoEtiquetasDAT_EDICAO: TDateField;
    tbImportacaoEtiquetasNOM_ASSINANTE: TWideStringField;
    tbImportacaoEtiquetasNOM_CUIDADOS: TWideStringField;
    tbImportacaoEtiquetasDES_ENDERECO: TWideStringField;
    tbImportacaoEtiquetasDES_COMPLEMENTO: TWideStringField;
    tbImportacaoEtiquetasDES_BAIRRO: TWideStringField;
    tbImportacaoEtiquetasDES_REFERENCIA: TWideStringField;
    tbImportacaoEtiquetasDES_CIDADE: TWideStringField;
    tbImportacaoEtiquetasDES_UF: TWideStringField;
    tbImportacaoEtiquetasCEP_ENDERECO: TWideStringField;
    tbImportacaoEtiquetasQTD_EXEMPLARES: TIntegerField;
    tbImportacaoEtiquetasCOD_BARRA: TWideStringField;
    tbImportacaoEtiquetasDOM_PROTOCOLO: TWideStringField;
    dsAssinantes: TDataSource;
    tbAtribuicoesID_ASSINANTE: TIntegerField;
    tbAtribuicoesCOD_BARRA: TStringField;
    tbAtribuicoesCOD_PRODUTO: TStringField;
    tbAtribuicoesCOD_TIPO_ASSINATURA: TStringField;
    tbAtribuicoesNUM_EDICAO: TStringField;
    tbAtribuicoesNOM_CUIDADOS: TStringField;
    tbAtribuicoesDES_UF: TStringField;
    tbAtribuicoesCOD_ASSINANTE: TStringField;
    dsAtribuicoes: TDataSource;
    tbAcareacoesSEQ_ACAREACAO: TIntegerField;
    tbAcareacoesID_ACAREACAO: TWideStringField;
    tbAcareacoesDAT_ACAREACAO: TDateTimeField;
    tbAcareacoesNUM_NOSSONUMERO: TWideStringField;
    tbAcareacoesCOD_ENTREGADOR: TIntegerField;
    tbAcareacoesNOM_ENTREGADOR: TWideStringField;
    tbAcareacoesCOD_BASE: TIntegerField;
    tbAcareacoesNOM_BASE: TWideStringField;
    tbAcareacoesDES_MOTIVO: TWideStringField;
    tbAcareacoesDES_TRATATIVA: TWideStringField;
    tbAcareacoesDES_APURACAO: TWideStringField;
    tbAcareacoesDES_RESULTADO: TWideStringField;
    tbAcareacoesVAL_EXTRAVIO: TFloatField;
    tbAcareacoesVAL_MULTA: TFloatField;
    tbAcareacoesDES_ENVIO_CORRESPONDENCIA: TWideStringField;
    tbAcareacoesDES_RETORNO_CORRESPONDENCIA: TWideStringField;
    tbAcareacoesDES_OBSERVACOES: TWideMemoField;
    tbEtiquetasID_ASSINANTE: TIntegerField;
    tbEtiquetasCOD_ASSINANTE: TStringField;
    tbEtiquetasCOD_PRODUTO: TStringField;
    tbEtiquetasNUM_EDICAO: TStringField;
    tbEtiquetasCOD_TIPO_ASSINATURA: TStringField;
    tbEtiquetasDAT_EDICAO: TDateField;
    tbEtiquetasNOM_ASSINANTE: TStringField;
    tbEtiquetasNOM_CUIDADOS: TStringField;
    tbEtiquetasDES_ENDERECO: TStringField;
    tbEtiquetasDES_COMPLEMENTO: TStringField;
    tbEtiquetasDES_BAIRRO: TStringField;
    tbEtiquetasDES_REFERENCIA: TStringField;
    tbEtiquetasDES_CIDADE: TStringField;
    tbEtiquetasDES_UF: TStringField;
    tbEtiquetasCEP_ENDERECO: TStringField;
    tbEtiquetasQTD_EXEMPLARES: TIntegerField;
    tbEtiquetasCOD_BARRA: TStringField;
    tbEtiquetasNUM_ROTEIRO: TIntegerField;
    tbEtiquetasNUM_ORDEM: TIntegerField;
    tbExtraviosCOD_EXTRAVIO: TIntegerField;
    tbExtraviosDES_EXTRAVIO: TWideStringField;
    tbExtraviosNUM_NOSSONUMERO: TWideStringField;
    tbExtraviosCOD_AGENTE: TIntegerField;
    tbExtraviosVAL_PRODUTO: TFloatField;
    tbExtraviosDAT_EXTRAVIO: TDateField;
    tbExtraviosVAL_MULTA: TFloatField;
    tbExtraviosVAL_VERBA: TFloatField;
    tbExtraviosVAL_TOTAL: TFloatField;
    tbExtraviosDOM_RESTRICAO: TWideStringField;
    tbExtraviosCOD_ENTREGADOR: TIntegerField;
    tbExtraviosNOM_EXECUTOR: TWideStringField;
    tbExtraviosDAT_MANUTENCAO: TDateTimeField;
    tbExtraviosCOD_TIPO: TIntegerField;
    tbExtraviosVAL_EXTRATO_FRANQUIA: TFloatField;
    tbExtraviosDES_ENVIO_CORRESPONDENCIA: TWideStringField;
    tbExtraviosDES_RETORNO_CORRESPONDENCIA: TWideStringField;
    tbExtraviosDES_OBSERVACOES: TWideMemoField;
    tbExtraviosNOM_ENTREGADOR: TWideStringField;
    tbExtraviosNOM_AGENTE: TWideStringField;
    tbAtribuicoesJornal: TdxMemData;
    tbAtribuicoesJornalID_ASSINANTE: TIntegerField;
    tbAtribuicoesJornalDAT_ATRIBUICAO: TDateField;
    tbAtribuicoesJornalCOD_PRODUTO: TWideStringField;
    tbAtribuicoesJornalNUM_EDICAO: TWideStringField;
    tbAtribuicoesJornalCOD_ASSINANTE: TWideStringField;
    tbAtribuicoesJornalCOD_TIPO_ASSINATURA: TWideStringField;
    tbAtribuicoesJornalCOD_ENTREGADOR: TIntegerField;
    tbAtribuicoesJornalNOM_ASSINANTE: TWideStringField;
    tbAtribuicoesJornalCOD_BARRA: TWideStringField;
    tbAtribuicoesJornalNOM_CUIDADOS: TWideStringField;
    tbAtribuicoesJornalDES_ENDERECO: TWideStringField;
    tbAtribuicoesJornalDES_COMPLEMENTO: TWideStringField;
    tbAtribuicoesJornalDES_BAIRRO: TWideStringField;
    tbAtribuicoesJornalDES_REFERENCIA: TWideStringField;
    tbAtribuicoesJornalDES_CIDADE: TWideStringField;
    tbAtribuicoesJornalDES_UF: TWideStringField;
    tbAtribuicoesJornalCEP_ENDERECO: TWideStringField;
    tbAtribuicoesJornalQTD_EXEMPLARES: TIntegerField;
    tbAtribuicoesJornalNUM_ROTEIRO: TIntegerField;
    tbAtribuicoesJornalNOM_USUARIO: TWideStringField;
    tbAtribuicoesJornalDAT_MANUTENCAO: TDateTimeField;
    tbAtribuicoesJornalDES_PRODUTO: TStringField;
    tbAtribuicoesJornalDES_TIPO_ASSINATURA: TStringField;
    tbEtiquetasID_REVISTA: TStringField;
    tbImportacaoEtiquetasID_REVISTA: TStringField;
    tbEtiquetasDES_ORDENACAO: TStringField;
    tbCRT: TdxMemData;
    tbCRTCOD_CRT: TIntegerField;
    tbCRTDES_CRT: TStringField;
    tbBancos: TdxMemData;
    tbBancosCOD_BANCO: TStringField;
    tbBancosNOM_BANCO: TStringField;
    tbContratos: TdxMemData;
    tbContratosCOD_TIPO_CONTRATO: TIntegerField;
    tbContratosDES_TIPO_CONTRATO: TStringField;
    tbContratosCOD_CENTRO_CUSTO: TIntegerField;
    tbCadastro: TdxMemData;
    tbCadastroCOD_CADASTRO: TIntegerField;
    tbCadastroDOM_FUNCIONARIO: TWideStringField;
    tbCadastroCOD_ENTREGADOR: TIntegerField;
    tbCadastroDES_TIPO_DOC: TWideStringField;
    tbCadastroDES_RAZAO_SOCIAL: TWideStringField;
    tbCadastroNOM_FANTASIA: TWideStringField;
    tbCadastroNUM_CNPJ: TWideStringField;
    tbCadastroNUM_IE: TWideStringField;
    tbCadastroDAT_NASCIMENTO: TDateTimeField;
    tbCadastroUF_RG: TWideStringField;
    tbCadastroDAT_EMISSAO_RG: TDateTimeField;
    tbCadastroUF_NASCIMENTO: TWideStringField;
    tbCadastroNOM_CIDADE_NASCIMENTO: TWideStringField;
    tbCadastroNOM_PAI: TWideStringField;
    tbCadastroNOM_MAE: TWideStringField;
    tbCadastroNUM_IEST: TWideStringField;
    tbCadastroNUM_IM: TWideStringField;
    tbCadastroCOD_CNAE: TWideStringField;
    tbCadastroCOD_CRT: TIntegerField;
    tbCadastroNUM_CNH: TWideStringField;
    tbCadastroNUM_REGISTRO_CNH: TWideStringField;
    tbCadastroDES_CATEGORIA_CNH: TWideStringField;
    tbCadastroDAT_VALIDADE_CNH: TDateField;
    tbCadastroUF_CNH: TWideStringField;
    tbCadastroDAT_1_HABILITACAO: TDateTimeField;
    tbCadastroDES_PAGINA: TWideStringField;
    tbCadastroCOD_AGENTE: TIntegerField;
    tbCadastroCOD_STATUS: TIntegerField;
    tbCadastroDES_OBSERVACAO: TWideMemoField;
    tbCadastroDAT_CADASTRO: TDateField;
    tbCadastroCOD_USUARIO: TIntegerField;
    tbCadastroVAL_VERBA: TFloatField;
    tbCadastroVAL_VERBA_COMBUSTIVEL: TFloatField;
    tbCadastroDES_TIPO_CONTA: TWideStringField;
    tbCadastroCOD_BANCO: TWideStringField;
    tbCadastroCOD_AGENCIA: TWideStringField;
    tbCadastroNUM_CONTA: TWideStringField;
    tbCadastroNOM_FAVORECIDO: TWideStringField;
    tbCadastroNUM_CPF_CNPJ_FAVORECIDO: TWideStringField;
    tbCadastroDES_FORMA_PAGAMENTO: TWideStringField;
    tbCadastroCOD_CENTRO_CUSTO: TIntegerField;
    tbCadastroDOM_VITIMA_ROUBO: TWideStringField;
    tbCadastroQTD_VITIMA_ROUBO: TIntegerField;
    tbCadastroDOM_ACIDENTES: TWideStringField;
    tbCadastroQTD_ACIDENTES: TIntegerField;
    tbCadastroDOM_TRANSPORTE_EMPRESA: TWideStringField;
    tbCadastroQTD_TRANSPORTE: TIntegerField;
    tbCadastroDOM_GV: TWideStringField;
    tbCadastroDAT_GV: TDateField;
    tbCadastroNOM_EXECUTANTE: TWideStringField;
    tbCadastroDAT_ALTERACAO: TDateTimeField;
    tbCadastroDES_CHAVE: TWideStringField;
    tbCadastroCOD_GRUPO: TIntegerField;
    tbAssinantesID_ASSINANTE: TIntegerField;
    tbAssinantesCOD_ASSINANTE: TWideStringField;
    tbAssinantesCOD_PRODUTO: TWideStringField;
    tbAssinantesCOD_TIPO_ASSINATURA: TWideStringField;
    tbAssinantesNUM_EDICAO: TWideStringField;
    tbAssinantesDAT_EDICAO: TDateField;
    tbAssinantesNOM_ASSINANTE: TWideStringField;
    tbAssinantesNOM_CUIDADOS: TWideStringField;
    tbAssinantesDES_ENDERECO: TWideStringField;
    tbAssinantesDES_COMPLEMENTO: TWideStringField;
    tbAssinantesDES_BAIRRO: TWideStringField;
    tbAssinantesDES_REFERENCIA: TWideStringField;
    tbAssinantesDES_CIDADE: TWideStringField;
    tbAssinantesDES_UF: TWideStringField;
    tbAssinantesCEP_ENDERECO: TWideStringField;
    tbAssinantesNUM_ROTEIRO: TIntegerField;
    tbAssinantesQTD_EXEMPLARES: TIntegerField;
    tbAssinantesCOD_BARRA: TWideStringField;
    tbAssinantesDOM_PROTOCOLO: TWideStringField;
    tbAssinantesID_REVISTA: TWideStringField;
    tbAssinantesDOM_BAIXA: TWideStringField;
    tbAssinantesNOM_RECEBEDOR: TWideStringField;
    tbAssinantesDES_GRAU_RELACIONAMENTO: TWideStringField;
    tbEtiquetasDOM_PROTOCOLO: TStringField;
    tbPesquisaEntregadorANO_EXERCICIO_CLRV: TStringField;
    tbTipoCadastro: TdxMemData;
    tbTipoCadastroCOD_TIPO_CADASTRO: TIntegerField;
    tbTipoCadastroDES_TIPO_CADASTRO: TStringField;
    tbSubTipo: TdxMemData;
    tbSubTipoCOD_SUB_TIPO: TIntegerField;
    tbSubTipoDES_SUB_TIPO: TStringField;
    tbDepartamentos: TdxMemData;
    tbDepartamentosCOD_DEPARTAMENTO: TIntegerField;
    tbDepartamentosDES_DEPARTAMENTO: TStringField;
    tbFiliais: TdxMemData;
    tbFiliaisCOD_FILIAL: TIntegerField;
    tbFiliaisDES_FILIAL: TStringField;
    tbFuncoes: TdxMemData;
    tbFuncoesCOD_FUNCAO: TIntegerField;
    tbFuncoesDES_FUNCAO: TStringField;
    tbUsuarios: TdxMemData;
    tbUsuariosCOD_USUARIO: TIntegerField;
    tbUsuariosNOM_USUARIO: TWideStringField;
    tbUsuariosDES_LOGIN: TWideStringField;
    tbUsuariosDES_EMAIL: TWideStringField;
    tbUsuariosDES_SENHA: TBlobField;
    tbUsuariosCOD_GRUPO: TIntegerField;
    tbUsuariosDOM_PRIVILEGIO: TWideStringField;
    tbUsuariosDOM_EXPIRA: TWideStringField;
    tbUsuariosQTD_DIAS_EXPIRA: TIntegerField;
    tbUsuariosDOM_PRIMEIRO_ACESSO: TWideStringField;
    tbUsuariosDOM_ATIVO: TWideStringField;
    tbUsuariosDAT_SENHA: TDateField;
    tbUsuariosCOD_NIVEL: TIntegerField;
    tbUsuariosNOM_EXECUTOR: TWideStringField;
    tbUsuariosDAT_MANUTENCAO: TDateTimeField;
    dxLayoutLookAndFeelList1: TdxLayoutLookAndFeelList;
    dxLayoutCxLookAndFeel1: TdxLayoutCxLookAndFeel;
    tbTipoOcorrencias: TdxMemData;
    tbAssinantesJornal: TdxMemData;
    tbAssinantesJornalID_ASSINANTE: TIntegerField;
    tbAssinantesJornalCOD_ASSINANTE: TWideStringField;
    tbAssinantesJornalCOD_MODALIDADE: TIntegerField;
    tbAssinantesJornalCOD_PRODUTO: TWideStringField;
    tbAssinantesJornalNUM_ORDEM: TIntegerField;
    tbAssinantesJornalQTD_EXEMPLARES: TIntegerField;
    tbAssinantesJornalNOM_ASSINANTE: TWideStringField;
    tbAssinantesJornalDES_TIPO_LOGRADOURO: TWideStringField;
    tbAssinantesJornalDES_LOGRADOURO: TWideStringField;
    tbAssinantesJornalNUM_LOGRADOURO: TWideStringField;
    tbAssinantesJornalDES_COMPLEMENTO: TWideStringField;
    tbAssinantesJornalNOM_BAIRRO: TWideStringField;
    tbAssinantesJornalNOM_CIDADE: TWideStringField;
    tbAssinantesJornalUF_ESTADO: TWideStringField;
    tbAssinantesJornalNUM_CEP: TWideStringField;
    tbAssinantesJornalDES_REFERENCIA: TWideStringField;
    tbAssinantesJornalDES_ROTEIRO: TWideStringField;
    tbAssinantesJornalDES_LOG: TWideMemoField;
    qryAccess: TZQuery;
    tbResumoLancamentos: TdxMemData;
    tbResumoLancamentosCOD_ENTREGADOR: TIntegerField;
    tbResumoLancamentosDES_TIPO: TWideStringField;
    tbResumoLancamentosVAL_LANCAMENTO: TFloatField;
    tbResumoLancamentosCHAVE: TStringField;
    tbTipoOcorrenciasCOD_TIPO_OCORRENCIA: TIntegerField;
    tbTipoOcorrenciasDES_TIPO_OCORRENCIA: TWideStringField;
    tbExtratoCOD_AGENTE: TIntegerField;
    tbExtratoDES_AGENTE: TWideStringField;
    tbExtratoCOD_ENTREGADOR: TIntegerField;
    tbExtratoDES_ENTREGADOR: TWideStringField;
    tbExtratoQTD_VOLUMES: TLargeintField;
    tbExtratoQTD_ENTREGA: TLargeintField;
    tbExtratoVAL_VERBA: TFloatField;
    tbExtratoVAL_VERBA_TOTAL: TFloatField;
    tbExtratoVAL_CREDITO: TFloatField;
    tbExtratoVAL_DEBITO: TFloatField;
    tbExtratoVAL_RESTRICAO: TFloatField;
    tbExtratoVAL_SUB_TOTAL: TFloatField;
    tbExtratoQTD_VOLUMES_EXTRA: TFloatField;
    tbExtratoVAL_VOLUMES_EXTRA: TFloatField;
    tbExtratoVAL_ABASTECIMENTO: TFloatField;
    tbExtratoVAL_PERCENTUAL_AGENTE: TFloatField;
    tbExtratoVAL_PERCENTUAL_ENTREGADOR: TFloatField;
    tbExtratoVAL_TOTAL: TFloatField;
    tbExtratoVAL_TOTAL_DESCONTOS: TFloatField;
    tbExtratoVAL_TOTAL_CREDITOS: TFloatField;
    tbExtratoVAL_TOTAL_GERAL: TFloatField;
    tbExtratoDAT_INICIO: TDateField;
    tbExtratoDAT_TERMINO: TDateField;
    tbExtratoDAT_INICIO_ABASTECIMENTO: TDateField;
    tbExtratoDAT_FINAL_ABASTECIMENTO: TDateField;
    tbExtratoDAT_PAGO: TDateField;
    tbExtratoNUM_EXTRATO: TWideStringField;
    tbExtratoQTD_ATRASOS: TLargeintField;
    tbExtratoQTD_2_DIAS: TLargeintField;
    tbExtratoQTD_MAIS_DIAS: TLargeintField;
    tbExtratoCOD_CADASTRO: TIntegerField;
    tbExtratoCOD_GRUPO_DISTRIBUIDOR: TIntegerField;
    tbExtratoVAL_VERBA_DISTRIBUIDOR: TFloatField;
    tbExtratoCOD_GRUPO_ENTREGADOR: TIntegerField;
    tbExtratoVAL_VERBA_ENTREGADOR: TFloatField;
    tbExtratoVAL_PERCENTUAL: TFloatField;
    tbResumoAbastecimento: TdxMemData;
    tbResumoAbastecimentoCOD_ENTREGADOR: TIntegerField;
    tbResumoAbastecimentoVAL_TOTAL: TFloatField;
    tbListaEntregadores: TdxMemData;
    tbListaEntregadoresCOD_CADASTRO: TIntegerField;
    tbListaEntregadoresDES_RAZAO_SOCIAL: TStringField;
    tbExtratoCOD_TIPO: TIntegerField;
    tbPesquisaEntregadorDES_PLACA: TStringField;
    tbPesquisaEntregadorDES_MODELO: TStringField;
    qryFaixasPesos: TZQuery;
    qryFaixaVerba: TZQuery;
    dsFaixasPesos: TDataSource;
    dsFaixaVerba: TDataSource;
    qryFaixasPesosID_VERBA: TIntegerField;
    qryFaixasPesosQTD_PESO_INICIAL: TFloatField;
    qryFaixasPesosQTD_PESO_FINAL: TFloatField;
    qryFaixasPesosDES_LOG: TWideMemoField;
    qryFaixaVerbaID_VERBA: TIntegerField;
    qryFaixaVerbaID_FAIXA: TIntegerField;
    qryFaixaVerbaVAL_VERBA: TFloatField;
    qryFaixaVerbaDES_LOG: TWideMemoField;
    qryCepDistribuidor: TZQuery;
    qryCepDistribuidorID_CEP: TIntegerField;
    qryCepDistribuidorCOD_DISTRIBUIDOR: TIntegerField;
    qryCepDistribuidorDES_CEP_INICIAL: TWideStringField;
    qryCepDistribuidorDES_CEP_FINAL: TWideStringField;
    qryCepDistribuidorDES_LOG: TWideMemoField;
    dsCepDistribuidor: TDataSource;
    dsCodigosEntregadores: TDataSource;
    qryCodigosEntregadores: TZQuery;
    qryCepVerba: TZQuery;
    qryCepVerbaID_VERBA: TIntegerField;
    qryCepVerbaNUM_CEP_INICIAL: TWideStringField;
    qryCepVerbaNUM_CEP_FINAL: TWideStringField;
    qryCepVerbaVAL_VERBA: TFloatField;
    qryCepVerbaCOD_GRUPO: TIntegerField;
    qryCepVerbaID_FAIXA: TIntegerField;
    qryCepVerbaDES_LOG: TWideMemoField;
    cxLocalizer: TcxLocalizer;
    qryRecados: TZQuery;
    qryResultadosRecados: TZQuery;
    qryResultadosRecadosCOD_RESULTADO: TIntegerField;
    qryResultadosRecadosDES_RESULTADO: TWideStringField;
    qryResultadosRecadosDES_LOG: TWideMemoField;
    qryOrigensResultadosRecados: TZQuery;
    qryOrigensResultadosRecadosCOD_ORIGEM: TIntegerField;
    qryOrigensResultadosRecadosDES_ORIGEM: TWideStringField;
    qryOrigensResultadosRecadosDOM_MOTIVO: TSmallintField;
    qryOrigensResultadosRecadosDES_LOG: TWideMemoField;
    qryRecadosID_RECADO: TIntegerField;
    qryRecadosDAT_OCORRENCIA: TDateField;
    qryRecadosCOD_ASSINATURA: TWideStringField;
    qryRecadosNOM_ASSINANTE: TWideStringField;
    qryRecadosDES_ENDERECO: TWideStringField;
    qryRecadosDES_RECADO: TWideMemoField;
    qryRecadosCOD_RESULTADO: TIntegerField;
    qryRecadosCOD_ORIGEM: TIntegerField;
    qryRecadosDES_MOTIVO: TWideMemoField;
    qryRecadosDES_ROTEIRO: TWideStringField;
    qryRecadosDES_PRODUTO: TWideStringField;
    qryRecadosDOM_IMPRESSAO: TWideStringField;
    qryRecadosDES_LOG: TWideMemoField;
    qryProdutosJornal: TZQuery;
    qryProdutosJornalCOD_PRODUTO: TWideStringField;
    qryProdutosJornalDES_PRODUTO: TWideStringField;
    qryCodigosEntregadoresCOD_CADASTRO: TIntegerField;
    qryCodigosEntregadoresCOD_ENTREGADOR: TIntegerField;
    qryCodigosEntregadoresNOM_FANTASIA: TWideStringField;
    qryCodigosEntregadoresCOD_AGENTE: TIntegerField;
    qryCodigosEntregadoresDAT_CODIGO: TDateField;
    qryCodigosEntregadoresDES_CHAVE: TWideStringField;
    qryCodigosEntregadoresCOD_GRUPO: TIntegerField;
    qryCodigosEntregadoresVAL_VERBA: TFloatField;
    qryCodigosEntregadoresNOM_EXECUTANTE: TWideStringField;
    qryCodigosEntregadoresDAT_MANUTENCAO: TDateTimeField;
    qryClientes: TZQuery;
    qryClientesCOD_CLIENTE: TIntegerField;
    qryClientesNOM_CLIENTE: TWideStringField;
    qryAgentes: TZQuery;
    qryAgentesCOD_AGENTE: TIntegerField;
    qryAgentesDES_RAZAO_SOCIAL: TWideStringField;
    qryAgentesNOM_FANTASIA: TWideStringField;
    qryAgentesDES_TIPO_DOC: TWideStringField;
    qryAgentesNUM_CNPJ: TWideStringField;
    qryAgentesNUM_IE: TWideStringField;
    qryAgentesNUM_IEST: TWideStringField;
    qryAgentesNUM_IM: TWideStringField;
    qryAgentesCOD_CNAE: TWideStringField;
    qryAgentesCOD_CRT: TIntegerField;
    qryAgentesNUM_CNH: TWideStringField;
    qryAgentesDES_CATEGORIA_CNH: TWideStringField;
    qryAgentesDAT_VALIDADE_CNH: TDateField;
    qryAgentesDES_PAGINA: TWideStringField;
    qryAgentesCOD_STATUS: TIntegerField;
    qryAgentesDES_OBSERVACAO: TWideMemoField;
    qryAgentesDAT_CADASTRO: TDateField;
    qryAgentesDAT_ALTERACAO: TDateTimeField;
    qryAgentesVAL_VERBA: TFloatField;
    qryAgentesDES_TIPO_CONTA: TWideStringField;
    qryAgentesCOD_BANCO: TWideStringField;
    qryAgentesCOD_AGENCIA: TWideStringField;
    qryAgentesNUM_CONTA: TWideStringField;
    qryAgentesNOM_FAVORECIDO: TWideStringField;
    qryAgentesNUM_CPF_CNPJ_FAVORECIDO: TWideStringField;
    qryAgentesDES_FORMA_PAGAMENTO: TWideStringField;
    qryAgentesCOD_CENTRO_CUSTO: TIntegerField;
    qryAgentesCOD_GRUPO: TIntegerField;
    qryControleTransporte: TZQuery;
    qryControleTransporteID_CONTROLE: TIntegerField;
    qryControleTransporteDAT_TRANSPORTE: TDateField;
    qryControleTransporteCOD_CLIENTE: TIntegerField;
    qryControleTransporteDES_OPERACAO: TWideStringField;
    qryControleTransporteDES_PLACA: TWideStringField;
    qryControleTransporteCOD_MOTORISTA: TIntegerField;
    qryControleTransporteQTD_KM_SAIDA: TFloatField;
    qryControleTransporteHOR_SAIDA: TTimeField;
    qryControleTransporteQTD_KM_RETORNO: TFloatField;
    qryControleTransporteHOR_RETORNO: TTimeField;
    qryControleTransporteQTD_KM_RODADO: TFloatField;
    qryControleTransporteDES_SERVICO: TWideStringField;
    qryControleTransporteDES_OBS: TWideMemoField;
    qryControleTransporteCOD_STATUS: TIntegerField;
    qryControleTransporteDES_LOG: TWideMemoField;
    qryVeiculos: TZQuery;
    qryVeiculosCOD_VEICULO: TIntegerField;
    qryVeiculosDES_TIPO_DOC: TWideStringField;
    qryVeiculosNUM_CNPJ: TWideStringField;
    qryVeiculosNOM_PROPRIETARIO: TWideStringField;
    qryVeiculosDAT_NASCIMENTO: TDateField;
    qryVeiculosNOM_MAE: TWideStringField;
    qryVeiculosNOM_PAI: TWideStringField;
    qryVeiculosNUM_RG: TWideStringField;
    qryVeiculosUF_RG: TWideStringField;
    qryVeiculosDAT_EMISSAO_RG: TDateField;
    qryVeiculosUF_ENDERECO: TWideStringField;
    qryVeiculosNOM_CIDADE: TWideStringField;
    qryVeiculosDES_ENDERECO: TWideStringField;
    qryVeiculosNUM_CEP: TWideStringField;
    qryVeiculosDES_BAIRRO: TWideStringField;
    qryVeiculosNUM_TELEFONE_1: TWideStringField;
    qryVeiculosDES_TELEFONE_1: TWideStringField;
    qryVeiculosNUM_TELEFONE_2: TWideStringField;
    qryVeiculosDES_TELEFONE_2: TWideStringField;
    qryVeiculosCOD_ENTREGADOR: TIntegerField;
    qryVeiculosDES_MARCA: TWideStringField;
    qryVeiculosDES_MODELO: TWideStringField;
    qryVeiculosDES_PLACA: TWideStringField;
    qryVeiculosUF_PLACA: TWideStringField;
    qryVeiculosNOM_CIDADE_PLACA: TWideStringField;
    qryVeiculosDES_TIPO: TWideStringField;
    qryVeiculosNUM_CHASSIS: TWideStringField;
    qryVeiculosDES_ANO: TWideStringField;
    qryVeiculosDES_COR: TWideStringField;
    qryVeiculosNUM_RENAVAN: TWideStringField;
    qryVeiculosANO_EXERCICIO_CLRV: TWideStringField;
    qryVeiculosDOM_RASTREAMENTO: TWideStringField;
    qryVeiculosDOM_ABASTECIMENTO: TWideStringField;
    qryVeiculosNOM_EXECUTOR: TWideStringField;
    qryVeiculosDAT_MANUTENCAO: TDateTimeField;
    qryEntregadores: TZQuery;
    qryEntregadoresCOD_CADASTRO: TIntegerField;
    qryEntregadoresDOM_FUNCIONARIO: TWideStringField;
    qryEntregadoresCOD_ENTREGADOR: TIntegerField;
    qryEntregadoresDES_TIPO_DOC: TWideStringField;
    qryEntregadoresDES_RAZAO_SOCIAL: TWideStringField;
    qryEntregadoresNOM_FANTASIA: TWideStringField;
    qryEntregadoresNUM_CNPJ: TWideStringField;
    qryEntregadoresNUM_IE: TWideStringField;
    qryEntregadoresDAT_NASCIMENTO: TDateTimeField;
    qryEntregadoresUF_RG: TWideStringField;
    qryEntregadoresDAT_EMISSAO_RG: TDateTimeField;
    qryEntregadoresUF_NASCIMENTO: TWideStringField;
    qryEntregadoresNOM_CIDADE_NASCIMENTO: TWideStringField;
    qryEntregadoresNOM_PAI: TWideStringField;
    qryEntregadoresNOM_MAE: TWideStringField;
    qryEntregadoresNUM_IEST: TWideStringField;
    qryEntregadoresNUM_IM: TWideStringField;
    qryEntregadoresCOD_CNAE: TWideStringField;
    qryEntregadoresCOD_CRT: TIntegerField;
    qryEntregadoresNUM_CNH: TWideStringField;
    qryEntregadoresNUM_REGISTRO_CNH: TWideStringField;
    qryEntregadoresDES_CATEGORIA_CNH: TWideStringField;
    qryEntregadoresDAT_VALIDADE_CNH: TDateField;
    qryEntregadoresUF_CNH: TWideStringField;
    qryEntregadoresDAT_1_HABILITACAO: TDateTimeField;
    qryEntregadoresDES_PAGINA: TWideStringField;
    qryEntregadoresCOD_AGENTE: TIntegerField;
    qryEntregadoresCOD_STATUS: TIntegerField;
    qryEntregadoresDES_OBSERVACAO: TWideMemoField;
    qryEntregadoresDAT_CADASTRO: TDateField;
    qryEntregadoresCOD_USUARIO: TIntegerField;
    qryEntregadoresVAL_VERBA: TFloatField;
    qryEntregadoresVAL_VERBA_COMBUSTIVEL: TFloatField;
    qryEntregadoresDES_TIPO_CONTA: TWideStringField;
    qryEntregadoresCOD_BANCO: TWideStringField;
    qryEntregadoresCOD_AGENCIA: TWideStringField;
    qryEntregadoresNUM_CONTA: TWideStringField;
    qryEntregadoresNOM_FAVORECIDO: TWideStringField;
    qryEntregadoresNUM_CPF_CNPJ_FAVORECIDO: TWideStringField;
    qryEntregadoresDES_FORMA_PAGAMENTO: TWideStringField;
    qryEntregadoresCOD_CENTRO_CUSTO: TIntegerField;
    qryEntregadoresDOM_VITIMA_ROUBO: TWideStringField;
    qryEntregadoresQTD_VITIMA_ROUBO: TIntegerField;
    qryEntregadoresDOM_ACIDENTES: TWideStringField;
    qryEntregadoresQTD_ACIDENTES: TIntegerField;
    qryEntregadoresDOM_TRANSPORTE_EMPRESA: TWideStringField;
    qryEntregadoresQTD_TRANSPORTE: TIntegerField;
    qryEntregadoresDOM_GV: TWideStringField;
    qryEntregadoresDAT_GV: TDateField;
    qryEntregadoresNOM_EXECUTANTE: TWideStringField;
    qryEntregadoresDAT_ALTERACAO: TDateTimeField;
    qryEntregadoresDES_CHAVE: TWideStringField;
    qryEntregadoresCOD_GRUPO: TIntegerField;
    qryEntregadoresCOD_ROTEIRO: TWideStringField;
    qryControleTransporteVAL_SERVICO: TFloatField;
    qryROEntregadores: TZReadOnlyQuery;
    qryROEntregadoresCOD_CADASTRO: TIntegerField;
    qryROEntregadoresDOM_FUNCIONARIO: TWideStringField;
    qryROEntregadoresCOD_ENTREGADOR: TIntegerField;
    qryROEntregadoresDES_TIPO_DOC: TWideStringField;
    qryROEntregadoresDES_RAZAO_SOCIAL: TWideStringField;
    qryROEntregadoresNOM_FANTASIA: TWideStringField;
    qryROEntregadoresNUM_CNPJ: TWideStringField;
    qryROEntregadoresNUM_IE: TWideStringField;
    qryROEntregadoresDAT_NASCIMENTO: TDateTimeField;
    qryROEntregadoresUF_RG: TWideStringField;
    qryROEntregadoresDAT_EMISSAO_RG: TDateTimeField;
    qryROEntregadoresUF_NASCIMENTO: TWideStringField;
    qryROEntregadoresNOM_CIDADE_NASCIMENTO: TWideStringField;
    qryROEntregadoresNOM_PAI: TWideStringField;
    qryROEntregadoresNOM_MAE: TWideStringField;
    qryROEntregadoresNUM_IEST: TWideStringField;
    qryROEntregadoresNUM_IM: TWideStringField;
    qryROEntregadoresCOD_CNAE: TWideStringField;
    qryROEntregadoresCOD_CRT: TIntegerField;
    qryROEntregadoresNUM_CNH: TWideStringField;
    qryROEntregadoresNUM_REGISTRO_CNH: TWideStringField;
    qryROEntregadoresDES_CATEGORIA_CNH: TWideStringField;
    qryROEntregadoresDAT_VALIDADE_CNH: TDateField;
    qryROEntregadoresUF_CNH: TWideStringField;
    qryROEntregadoresDAT_1_HABILITACAO: TDateTimeField;
    qryROEntregadoresDES_PAGINA: TWideStringField;
    qryROEntregadoresCOD_AGENTE: TIntegerField;
    qryROEntregadoresCOD_STATUS: TIntegerField;
    qryROEntregadoresDES_OBSERVACAO: TWideMemoField;
    qryROEntregadoresDAT_CADASTRO: TDateField;
    qryROEntregadoresCOD_USUARIO: TIntegerField;
    qryROEntregadoresVAL_VERBA: TFloatField;
    qryROEntregadoresVAL_VERBA_COMBUSTIVEL: TFloatField;
    qryROEntregadoresDES_TIPO_CONTA: TWideStringField;
    qryROEntregadoresCOD_BANCO: TWideStringField;
    qryROEntregadoresCOD_AGENCIA: TWideStringField;
    qryROEntregadoresNUM_CONTA: TWideStringField;
    qryROEntregadoresNOM_FAVORECIDO: TWideStringField;
    qryROEntregadoresNUM_CPF_CNPJ_FAVORECIDO: TWideStringField;
    qryROEntregadoresDES_FORMA_PAGAMENTO: TWideStringField;
    qryROEntregadoresCOD_CENTRO_CUSTO: TIntegerField;
    qryROEntregadoresDOM_VITIMA_ROUBO: TWideStringField;
    qryROEntregadoresQTD_VITIMA_ROUBO: TIntegerField;
    qryROEntregadoresDOM_ACIDENTES: TWideStringField;
    qryROEntregadoresQTD_ACIDENTES: TIntegerField;
    qryROEntregadoresDOM_TRANSPORTE_EMPRESA: TWideStringField;
    qryROEntregadoresQTD_TRANSPORTE: TIntegerField;
    qryROEntregadoresDOM_GV: TWideStringField;
    qryROEntregadoresDAT_GV: TDateField;
    qryROEntregadoresNOM_EXECUTANTE: TWideStringField;
    qryROEntregadoresDAT_ALTERACAO: TDateTimeField;
    qryROEntregadoresDES_CHAVE: TWideStringField;
    qryROEntregadoresCOD_GRUPO: TIntegerField;
    qryROEntregadoresCOD_ROTEIRO: TWideStringField;
    qryROServicos: TZReadOnlyQuery;
    qryROServicosCOD_SERVICO: TIntegerField;
    qryROServicosDES_SERVICO: TWideStringField;
    qryROServicosDOM_AGREGACAO: TWideStringField;
    qryROServicosVAL_SERVICO: TFloatField;
    qryROAgentes: TZReadOnlyQuery;
    qryROAgentesCOD_AGENTE: TIntegerField;
    qryROAgentesDES_RAZAO_SOCIAL: TWideStringField;
    qryROAgentesNOM_FANTASIA: TWideStringField;
    qryROAgentesDES_TIPO_DOC: TWideStringField;
    qryROAgentesNUM_CNPJ: TWideStringField;
    qryROAgentesNUM_IE: TWideStringField;
    qryROAgentesNUM_IEST: TWideStringField;
    qryROAgentesNUM_IM: TWideStringField;
    qryROAgentesCOD_CNAE: TWideStringField;
    qryROAgentesCOD_CRT: TIntegerField;
    qryROAgentesNUM_CNH: TWideStringField;
    qryROAgentesDES_CATEGORIA_CNH: TWideStringField;
    qryROAgentesDAT_VALIDADE_CNH: TDateField;
    qryROAgentesDES_PAGINA: TWideStringField;
    qryROAgentesCOD_STATUS: TIntegerField;
    qryROAgentesDES_OBSERVACAO: TWideMemoField;
    qryROAgentesDAT_CADASTRO: TDateField;
    qryROAgentesDAT_ALTERACAO: TDateTimeField;
    qryROAgentesVAL_VERBA: TFloatField;
    qryROAgentesDES_TIPO_CONTA: TWideStringField;
    qryROAgentesCOD_BANCO: TWideStringField;
    qryROAgentesCOD_AGENCIA: TWideStringField;
    qryROAgentesNUM_CONTA: TWideStringField;
    qryROAgentesNOM_FAVORECIDO: TWideStringField;
    qryROAgentesNUM_CPF_CNPJ_FAVORECIDO: TWideStringField;
    qryROAgentesDES_FORMA_PAGAMENTO: TWideStringField;
    qryROAgentesCOD_CENTRO_CUSTO: TIntegerField;
    qryROAgentesCOD_GRUPO: TIntegerField;
    qryAbastecimentos: TZQuery;
    qryAbastecimentosNUM_ABASTECIMENTO: TIntegerField;
    qryAbastecimentosNUM_CUPOM: TWideStringField;
    qryAbastecimentosCOD_ENTREGADOR: TIntegerField;
    qryAbastecimentosDES_PLACA: TWideStringField;
    qryAbastecimentosDAT_ABASTECIMENTO: TDateField;
    qryAbastecimentosDES_PRODUTO: TWideStringField;
    qryAbastecimentosQTD_ABASTECIMENTO: TFloatField;
    qryAbastecimentosVAL_UNITARIO: TFloatField;
    qryAbastecimentosVAL_TOTAL: TFloatField;
    qryAbastecimentosNOM_EXECUTANTE: TWideStringField;
    qryAbastecimentosDAT_MANUTENCAO: TDateTimeField;
    qryAbastecimentosDOM_DESCONTO: TWideStringField;
    qryAbastecimentosNUM_EXTRATO: TWideStringField;
    qryAbastecimentosVAL_VERBA_COMBUSTIVEL: TFloatField;
    qryAbastecimentosVAL_DESCONTO: TFloatField;
    qryAbastecimentosDAT_BASE: TDateField;
    qryAbastecimentosNOM_ENTREGADOR: TWideStringField;
    qryAbastecimentosID_CONTROLE: TIntegerField;
    qryROClientes: TZReadOnlyQuery;
    qryROClientesCOD_CLIENTE: TIntegerField;
    qryROClientesNOM_CLIENTE: TWideStringField;
    qryROClientesDOM_OS: TIntegerField;
    dxSkinController1: TdxSkinController;
    cxHintStyleController: TcxHintStyleController;
    iml16x16: TcxImageList;
    iml32x32: TcxImageList;
    tbDistribuidorVA: TdxMemData;
    tbDistribuidorVAID_DISTRIBUIDOR: TIntegerField;
    tbDistribuidorVACOD_DISTRIBUIDOR: TIntegerField;
    tbDistribuidorVANOM_DISTRIBUIDOR: TStringField;
    tbListaBancas: TdxMemData;
    tbListaBancasCOD_BANCA: TIntegerField;
    tbListaBancasCOD_DISTRIBUIDOR: TIntegerField;
    tbListaBancasNOM_BANCA: TStringField;
    FDConn: TFDConnection;
    FDGUIxWaitCursor: TFDGUIxWaitCursor;
    FDGUIxAsyncExecuteDialog: TFDGUIxAsyncExecuteDialog;
    fdqProdutosVA: TFDQuery;
    fdqBancas: TFDQuery;
    fdqDistribuidor: TFDQuery;
    fdqDistribuidorID_DISTRIBUIDOR: TIntegerField;
    fdqDistribuidorCOD_DISTRIBUIDOR: TIntegerField;
    fdqDistribuidorNOM_DISTRIBUIDOR: TStringField;
    fdqDistribuidorDES_LOG: TMemoField;
    FDBatchMoveRemessa: TFDBatchMove;
    FDBatchMoveTextReaderRemessa: TFDBatchMoveTextReader;
    FDBatchMoveDataSetWriterRemessa: TFDBatchMoveDataSetWriter;
    fdmRemessa: TFDMemTable;
    fdmRemessaCOD_BANCA: TStringField;
    fdmRemessaDAT_CIRCULACAO: TStringField;
    fdmRemessaCOD_PRODUTO: TStringField;
    fdmRemessaDES_PRODUTO: TStringField;
    fdmRemessaQTD_REMESSA: TStringField;
    dsImportaRemessa: TDataSource;
    fdqRemessasVA: TFDQuery;
    fdqRemessasVAID_REMESSAS: TIntegerField;
    fdqRemessasVACOD_DISTRIBUIDOR: TIntegerField;
    fdqRemessasVACOD_BANCA: TIntegerField;
    fdqRemessasVACOD_PRODUTO: TStringField;
    fdqRemessasVADAT_REMESSA: TDateField;
    fdqRemessasVANUM_REMESSA: TStringField;
    fdqRemessasVAQTD_REMESSA: TSingleField;
    fdqRemessasVADAT_RECOBERTURA: TDateField;
    fdqRemessasVAQTD_RECOBERTURA: TSingleField;
    fdqRemessasVADAT_CHAMADA: TDateField;
    fdqRemessasVANUM_DEVOLUCAO: TStringField;
    fdqRemessasVAQTD_ENCALHE: TSingleField;
    fdqRemessasVAVAL_COBRANCA: TSingleField;
    fdqRemessasVAVAL_VENDA: TSingleField;
    fdqRemessasVADOM_INVENTARIO: TShortintField;
    fdqRemessasVADES_LOG: TMemoField;
    fdqProdutosVAID_PRODUTO: TFDAutoIncField;
    fdqProdutosVACOD_PRODUTO: TStringField;
    fdqProdutosVADES_PRODUTO: TStringField;
    fdqProdutosVAQTD_PADRAO: TIntegerField;
    fdqProdutosVADOM_DIARIO: TShortintField;
    fdqProdutosVACOD_BARRAS: TStringField;
    fdqProdutosVADES_LOG: TMemoField;
    mtbExtravios: TdxMemData;
    mtbExtraviosCOD_EXTRAVIO: TIntegerField;
    mtbExtraviosDES_EXTRAVIO: TWideStringField;
    mtbExtraviosNUM_NOSSONUMERO: TWideStringField;
    mtbExtraviosCOD_AGENTE: TIntegerField;
    mtbExtraviosVAL_PRODUTO: TFloatField;
    mtbExtraviosDAT_EXTRAVIO: TDateField;
    mtbExtraviosVAL_MULTA: TFloatField;
    mtbExtraviosVAL_VERBA: TFloatField;
    mtbExtraviosVAL_TOTAL: TFloatField;
    mtbExtraviosDOM_RESTRICAO: TWideStringField;
    mtbExtraviosCOD_ENTREGADOR: TIntegerField;
    mtbExtraviosCOD_TIPO: TIntegerField;
    mtbExtraviosVAL_EXTRATO_FRANQUIA: TFloatField;
    mtbExtraviosDOM_EXTRATO_FRANQUIA: TStringField;
    mtbExtraviosDAT_EXTRAVIO_FRANQUIA: TDateField;
    mtbExtraviosDES_ENVIO_CORRESPONDENCIA: TWideStringField;
    mtbExtraviosDES_RETORNO_CORRESPONDENCIA: TWideStringField;
    mtbExtraviosDES_OBSERVACOES: TWideMemoField;
    mtbExtraviosNOM_EXECUTOR: TWideStringField;
    mtbExtraviosDAT_MANUTENCAO: TDateTimeField;
    mtbExtraviosVAL_PERCENTUAL_PAGO: TFloatField;
    tbParLocalQTD_RAIO_X: TIntegerField;
    frxReport: TfrxReport;
    frxPDFExport1: TfrxPDFExport;
    frxHTMLExport1: TfrxHTMLExport;
    frxRTFExport1: TfrxRTFExport;
    frxBMPExport1: TfrxBMPExport;
    frxJPEGExport1: TfrxJPEGExport;
    frxTIFFExport1: TfrxTIFFExport;
    frxGIFExport1: TfrxGIFExport;
    frxSimpleTextExport1: TfrxSimpleTextExport;
    frxCSVExport1: TfrxCSVExport;
    frxDBDataset: TfrxDBDataset;
    procedure qryFaixasPesosBeforePost(DataSet: TDataSet);
    procedure qryFaixaVerbaBeforePost(DataSet: TDataSet);
    procedure qryFaixaVerbaAfterInsert(DataSet: TDataSet);
    procedure qryFaixasPesosBeforeDelete(DataSet: TDataSet);
    procedure qryCepDistribuidorBeforePost(DataSet: TDataSet);
    procedure qryCepDistribuidorBeforeDelete(DataSet: TDataSet);
    procedure qryCepVerbaBeforePost(DataSet: TDataSet);
    procedure qryCepVerbaBeforeDelete(DataSet: TDataSet);
    procedure DataModuleCreate(Sender: TObject);
    procedure qryRecadosBeforePost(DataSet: TDataSet);
    procedure qryControleTransporteBeforePost(DataSet: TDataSet);
    procedure FDConnBeforeConnect(Sender: TObject);
  private
    { Private declarations }
  public
    { Public declarations }
  end;

var
  dm: Tdm;

implementation

{$R *.dfm}

uses uGlobais, Global.Parametros;

procedure Tdm.DataModuleCreate(Sender: TObject);
var
  iKey: Integer;
begin
  iKey := 0;
  uGlobais.sIni := ExtractFilePath(Application.ExeName) + 'database.ini';
  Global.Parametros.pFileIni := ExtractFilePath(Application.ExeName) + 'database.ini';
  if FileExists(Global.Parametros.pFileIni) then
  begin
    Global.Parametros.pDriverID := TUtil.LeIni( Global.Parametros.pFileIni, 'Database', 'DriverID');
    Global.Parametros.pServer := TUtil.LeIni( Global.Parametros.pFileIni, 'Database', 'HostName');
    Global.Parametros.pCatalog := TUtil.LeIni( Global.Parametros.pFileIni, 'Database', 'Catalog');
    Global.Parametros.pDatabase := TUtil.LeIni( Global.Parametros.pFileIni, 'Database', 'Database');
    Global.Parametros.pPort := TUtil.LeIni( Global.Parametros.pFileIni, 'Database', 'Port');
    iKey := StrToInt(TUtil.LeIni( Global.Parametros.pFileIni, 'Database', 'KBD'));
    Global.Parametros.pKBD := IntToStr(iKey);
    Global.Parametros.pUBD := TUtil.DesCriptografa(TUtil.LeIni( Global.Parametros.pFileIni, 'Database', 'UBD'), iKey);
    Global.Parametros.pPBD := TUtil.DesCriptografa(TUtil.LeIni( Global.Parametros.pFileIni, 'Database', 'PBD'), iKey);
  end;

  if FileExists(ExtractFilePath(Application.ExeName)+'\devtrans.ini') then
  begin
    cxLocalizer.LoadFromFile(ExtractFilePath(Application.ExeName)+ '\devtrans.ini');
    cxLocalizer.LanguageIndex := 1; // MUDA DE LINGUAGEM
    cxLocalizer.Active := TRUE;     // ATIVA O COMPONENTE
  end;
end;

procedure Tdm.FDConnBeforeConnect(Sender: TObject);
begin
  FDConn.ConnectionString := 'DriverID=' + Global.Parametros.pDriverID +
                                     ';Server=' + Global.Parametros.pServer +
                                     ';Database=' + Global.Parametros.pDatabase +
                                     ';Port=' + Global.Parametros.pPort +
                                     ';User_name=' + Global.Parametros.pUBD +
                                     ';Password=' + Global.Parametros.pPBD;
end;

procedure Tdm.qryCepDistribuidorBeforeDelete(DataSet: TDataSet);
begin
  if Application.MessageBox('Confirma a exclusão?', PChar('Atenção ' + uGlobais.sUsuario), MB_YESNO + MB_ICONQUESTION) = IDNO then
  begin
    Abort;
  end;
end;

procedure Tdm.qryCepDistribuidorBeforePost(DataSet: TDataSet);
var
  sLog : TStringList;
begin
  sLog := TStringList.Create;
  sLog.Append(DataSet.FieldByName('DES_LOG').asString);
  sLog.Add(FormatDateTime('dd/mm/yyyy hh:mm:ss',Now) + ' manutenção feita por ' + uGlobais.sUsuario);
  Dataset.FieldByName('DES_LOG').AsString := sLog.Text;
  sLog.Free;
end;

procedure Tdm.qryCepVerbaBeforeDelete(DataSet: TDataSet);
begin
  if Application.MessageBox('Confirma a exclusão?', PChar('Atenção ' + uGlobais.sUsuario), MB_YESNO + MB_ICONQUESTION) = IDNO then
  begin
    Abort;
  end;
end;

procedure Tdm.qryCepVerbaBeforePost(DataSet: TDataSet);
var
  sLog : TStringList;
begin
  sLog := TStringList.Create;
  sLog.Append(DataSet.FieldByName('DES_LOG').asString);
  sLog.Add(FormatDateTime('dd/mm/yyyy hh:mm:ss',Now) + ' manutenção feita por ' + uGlobais.sUsuario);
  Dataset.FieldByName('DES_LOG').AsString := sLog.Text;
  sLog.Free;
end;

procedure Tdm.qryControleTransporteBeforePost(DataSet: TDataSet);
var
  sLog : TStringList;
begin
  try
  sLog := TStringList.Create;
  sLog.Append(DataSet.FieldByName('DES_LOG').asString);
  sLog.Add(FormatDateTime('dd/mm/yyyy hh:mm:ss',Now) + ' manutenção feita por ' + uGlobais.sUsuario);
  Dataset.FieldByName('DES_LOG').AsString := sLog.Text;
  finally
    sLog.Free;
  end;
end;

procedure Tdm.qryFaixasPesosBeforeDelete(DataSet: TDataSet);
begin
  if Application.MessageBox('Confirma a exclusão?', PChar('Atenção ' + uGlobais.sUsuario), MB_YESNO + MB_ICONQUESTION) = IDNO then
  begin
    Abort;
  end;
end;

procedure Tdm.qryFaixasPesosBeforePost(DataSet: TDataSet);
var
  sLog : TStringList;
begin
  sLog := TStringList.Create;
  sLog.Append(DataSet.FieldByName('DES_LOG').asString);
  sLog.Add(FormatDateTime('dd/mm/yyyy hh:mm:ss',Now) + ' manutenção feita por ' + uGlobais.sUsuario);
  Dataset.FieldByName('DES_LOG').AsString := sLog.Text;
  sLog.Free;
end;

procedure Tdm.qryFaixaVerbaAfterInsert(DataSet: TDataSet);
var
  iRec : Integer;
begin
  iRec := Dataset.RecordCount + 1;
  DataSet.FieldByName('ID_FAIXA').AsInteger := iRec;
end;

procedure Tdm.qryFaixaVerbaBeforePost(DataSet: TDataSet);
var
  sLog : TStringList;
begin
  sLog := TStringList.Create;
  sLog.Append(DataSet.FieldByName('DES_LOG').asString);
  sLog.Add(FormatDateTime('dd/mm/yyyy hh:mm:ss',Now) + ' manutenção feita por ' + uGlobais.sUsuario);
  Dataset.FieldByName('DES_LOG').AsString := sLog.Text;
  sLog.Free;
end;

procedure Tdm.qryRecadosBeforePost(DataSet: TDataSet);
var
  sLog : TStringList;
begin
  if not TUtil.DataOk(DataSet.FieldByName('DAT_OCORRENCIA').AsString) then
  begin
    Application.MessageBox('Informe a data da ocorrência!', 'Atenção', MB_OK + MB_ICONEXCLAMATION);
    Abort;
    Exit;
  end;
  if TUtil.Empty(DataSet.FieldByName('COD_ASSINATURA').AsString) then
  begin
    Application.MessageBox('Informe a um código de assinatura!', 'Atenção', MB_OK + MB_ICONEXCLAMATION);
    Abort;
    Exit;
  end;
  if TUtil.Empty(DataSet.FieldByName('NOM_ASSINANTE').AsString) then
  begin
    Application.MessageBox('Informe o nome do assinante!', 'Atenção', MB_OK + MB_ICONEXCLAMATION);
    Abort;
    Exit;
  end;
  if TUtil.Empty(DataSet.FieldByName('DES_ENDERECO').AsString) then
  begin
    Application.MessageBox('Nenhum endereço informado!', 'Atenção', MB_OK + MB_ICONEXCLAMATION);
    Abort;
    Exit;
  end;
  if TUtil.Empty(DataSet.FieldByName('DES_PRODUTO').AsString) then
  begin
    Application.MessageBox('Nenhum Produto informado!', 'Atenção', MB_OK + MB_ICONEXCLAMATION);
    Abort;
    Exit;
  end;
  sLog := TStringList.Create;
  sLog.Append(DataSet.FieldByName('DES_LOG').asString);
  sLog.Add(FormatDateTime('dd/mm/yyyy hh:mm:ss',Now) + ' manutenção feita por ' + uGlobais.sUsuario);
  Dataset.FieldByName('DES_LOG').AsString := sLog.Text;
  sLog.Free;
end;

end.
