CREATE TABLE TBPLANILHACREDITO (
 SEQ_CREDITO INTEGER NOT NULL,
 DAT_PAGO DATE,
 NUM_EXTRATO VARCHAR(15),
 COD_AGENTE INTEGER,
 COD_ENTREGADOR INTEGER,
 DES_TIPO_CONTA VARCHAR(20),
 COD_BANCO VARCHAR(10),
 COD_AGENCIA VARCHAR(10),
 NUM_CONTA VARCHAR(20),
 NOM_FAVORECIDO VARCHAR(70),
 NUM_CPF_CNPJ_FAVORECIDO VARCHAR(20),
 VAL_CREDITO FLOAT DEFAULT 0,
 DES_TIPO_PAGAMENTO VARCHAR(20),
 NOM_EXECUTOR VARCHAR(20) DEFAULT 'SISTEMA',
 DAT_MANUTENCAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE TBPLANILHACREDITO ADD CONSTRAINT PK_TBPLANILHACREDITO PRIMARY KEY (SEQ_CREDITO);

CREATE INDEX TBPLANILHACREDITO_IDX1 ON TBPLANILHACREDITO (DAT_PAGO);
CREATE INDEX TBPLANILHACREDITO_IDX2 ON TBPLANILHACREDITO (NUM_EXTRATO);
CREATE INDEX TBPLANILHACREDITO_IDX3 ON TBPLANILHACREDITO (COD_AGENTE);
CREATE INDEX TBPLANILHACREDITO_IDX4 ON TBPLANILHACREDITO (COD_ENTREGADOR);
CREATE INDEX TBPLANILHACREDITO_IDX5 ON TBPLANILHACREDITO (COD_BANCO);
CREATE INDEX TBPLANILHACREDITO_IDX6 ON TBPLANILHACREDITO (NOM_FAVORECIDO);
CREATE INDEX TBPLANILHACREDITO_IDX7 ON TBPLANILHACREDITO (DES_TIPO_PAGAMENTO);
CREATE INDEX TBPLANILHACREDITO_IDX8 ON TBPLANILHACREDITO (NUM_CPF_CNPJ_FAVORECIDO);


