set names none;

set sql dialect 3;

set clientlib 'gds32.dll';

connect 'C:\Projetos\Delphi\OO\SGE2\Database\DBSGE2.FDB'
user 'SYSDBA' password 'masterkey';

CREATE TABLE TBORDEMSERVICO (
 NUM_OS INTEGER NOT NULL,
 DAT_OS DATE,
 COD_ENTREGADOR INTEGER DEFAULT 0,
 COD_VEICULO INTEGER DEFAULT 0,
 DES_ROTA VARCHAR(50),
 QTD_KM_INICIAL INTEGER DEFAULT 0,
 QTD_KM_FINAL INTEGER DEFAULT 0,
 DES_HORA_SAIDA CHAR(5) DEFAULT '00:00',
 DES_HORA_RETORNO CHAR(5) DEFAULT '00:00',
 DES_SERVICO BLOB SUB_TYPE 1 SEGMENT SIZE 16384,
 VAL_DIARIA DOUBLE PRECISION DEFAULT 0,
 NOM_EXECUTOR VARCHAR(20) DEFAULT 'SISTEMA',
 DAT_MANUTENCAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE TBORDEMSERVICO ADD CONSTRAINT PK_TBORDEMSERVICO PRIMARY KEY (NUM_OS);

CREATE INDEX TBORDEMSERVICO_IDX1 ON TBORDEMSERVICO (DAT_OS);



