CREATE TABLE TBCONTROLEKM (
 SEQ_CONTROLE INTEGER NOT NULL,
 DAT_CONTROLE DATE,
 COD_VEICULO INTEGER DEFAULT 0,
 QTD_KM_INICIAL INTEGER DEFAULT 0,
 DES_HORA_SAIDA CHAR(5) DEFAULT '00:00',
 QTD_KM_FINAL INTEGER DEFAULT 0,
 DES_HORA_RETORNO CHAR(5) DEFAULT '00:00',
 COD_ENTREGADOR INTEGER DEFAULT 0,
 DES_OBSERVACOES VARCHAR(256),
 NOM_EXECUTOR VARCHAR(20) DEFAULT 'SISTEMA',
 DAT_MANUTENCAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE TBCONTROLEKM ADD CONSTRAINT PK_TBCONTROLEKM PRIMARY KEY (SEQ_CONTROLE);


