set names none;

set sql dialect 3;

set clientlib 'gds32.dll';

connect '192.168.1.5:C:\Database\SGE2\DBSGE2.FDB'
user 'SYSDBA' password 'masterkey';

CREATE TABLE TBVERBACEP (
 NUM_CEP VARCHAR(9) NOT NULL,
 VAL_VERBA DOUBLE PRECISION DEFAULT 0,
 NOM_EXECUTOR VARCHAR(20) DEFAULT 'SISTEMA',
 DAT_MANUTENCAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE TBVERBACEP ADD CONSTRAINT PK_TBVERBACEP PRIMARY KEY (NUM_CEP);


