SELECT TBENTREGAS.COD_AGENTE AS AGENTE, TBAGENTES.NOM_FANTASIA AS NOME, 
COUNT(TBENTREGAS.NUM_NOSSONUMERO) AS ENTREGAS FROM TBENTREGAS 
INNER JOIN TBAGENTES ON TBENTREGAS.COD_AGENTE = TBAGENTES.COD_AGENTE 
WHERE TBENTREGAS.COD_CLIENTE = 99991 
AND TBENTREGAS.DOM_BAIXADO = 'S' AND TBENTREGAS.COD_STATUS = 12
GROUP BY TBENTREGAS.COD_AGENTE
