CREATE TABLE `tbcodigosentregadores` (
  `ID_REGISTRO` int(11) NOT NULL,
  `COD_CADASTRO` int(11) NOT NULL,
  `COD_ENTREGADOR` int(11) DEFAULT NULL,
  `NOM_FANTASIA` varchar(70) DEFAULT NULL,
  `COD_AGENTE` int(11) DEFAULT NULL,
  `DAT_CODIGO` date DEFAULT NULL,
  `DES_CHAVE` varchar(70) DEFAULT NULL,
  `NOM_EXECUTOR` varchar(20) DEFAULT 'SISTEMA',
  `DAT_MANUTENCAO` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID_REGISTRO`,`COD_CADASTRO`),
  KEY `TBCODIGOSENTREGARORES_IX1` (`COD_CADASTRO`),
  KEY `TBCODIGOSENTREGARORES_IX2` (`COD_ENTREGADOR`),
  KEY `TBCODIGOSENTREGARORES_IX3` (`NOM_FANTASIA`),
  KEY `TBCODIGOSENTREGARORES_IX4` (`COD_AGENTE`),
  KEY `TBCODIGOSENTREGARORES_IX5` (`DES_CHAVE`),
  KEY `TBCODIGOSENTREGARORES_IX6` (`DES_CHAVE`,`DAT_CODIGO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
