SELECT TBENTREGAS.COD_ENTREGADOR "CÓDIGO", 
TBENTREGADORES.NOM_FANTASIA "NOME", 
COUNT(TBENTREGAS.NUM_NOSSONUMERO) "ENTREGAS", 
SUM(TBENTREGAS.QTD_VOLUMES) "VOLUMES",  
SUM(IF((TBENTREGAS.QTD_DIAS_ATRASO = 1),1,0)) "1 DIA",
SUM(IF((TBENTREGAS.QTD_DIAS_ATRASO = 2),1,0)) "2 DIAS", 
SUM(IF((TBENTREGAS.QTD_DIAS_ATRASO >= 3),1,0)) "MAIS DE 2 DIAS"   
FROM TBENTREGAS 
LEFT JOIN TBENTREGADORES 
ON TBENTREGAS.COD_ENTREGADOR = TBENTREGADORES.COD_ENTREGADOR 
WHERE TBENTREGAS.DAT_BAIXA BETWEEN
'2014-07-11' AND '2014-07-25' AND
TBENTREGAS.DOM_BAIXADO = 'S' AND TBENTREGAS.COD_AGENTE = 1026
GROUP BY TBENTREGAS.COD_ENTREGADOR 