CREATE TABLE `tbentregadores` (
  `COD_CADASTRO` int(11) NOT NULL AUTO_INCREMENT,
  `DOM_FUNCIONARIO` varchar(1) COLLATE utf8_swedish_ci DEFAULT 'E',
  `COD_ENTREGADOR` int(11) DEFAULT '0',
  `DES_TIPO_DOC` varchar(4) COLLATE utf8_swedish_ci DEFAULT 'CNPJ',
  `DES_RAZAO_SOCIAL` varchar(70) COLLATE utf8_swedish_ci DEFAULT NULL,
  `NOM_FANTASIA` varchar(80) COLLATE utf8_swedish_ci DEFAULT NULL,
  `NUM_CNPJ` varchar(20) COLLATE utf8_swedish_ci DEFAULT NULL,
  `NUM_IE` varchar(20) COLLATE utf8_swedish_ci DEFAULT NULL,
  `UF_RG` varchar(2) COLLATE utf8_swedish_ci DEFAULT '',
  `DAT_EMISSAO_RG` datetime DEFAULT NULL,
  `UF_NASCIMENTO` varchar(2) COLLATE utf8_swedish_ci DEFAULT '',
  `NOM_CIDADE_NASCIMENTO` varchar(72) COLLATE utf8_swedish_ci DEFAULT '',
  `NOM_PAI` varchar(72) COLLATE utf8_swedish_ci DEFAULT '',
  `NOM_MAE` varchar(72) COLLATE utf8_swedish_ci DEFAULT '',
  `NUM_IEST` varchar(20) COLLATE utf8_swedish_ci DEFAULT NULL,
  `NUM_IM` varchar(20) COLLATE utf8_swedish_ci DEFAULT NULL,
  `COD_CNAE` varchar(10) COLLATE utf8_swedish_ci DEFAULT '0',
  `COD_CRT` int(11) DEFAULT NULL,
  `NUM_CNH` varchar(15) COLLATE utf8_swedish_ci DEFAULT NULL,
  `NUM_REGISTRO_CNH` varchar(15) COLLATE utf8_swedish_ci DEFAULT '',
  `DES_CATEGORIA_CNH` varchar(2) COLLATE utf8_swedish_ci DEFAULT NULL,
  `DAT_VALIDADE_CNH` date DEFAULT NULL,
  `UF_CNH` varchar(2) COLLATE utf8_swedish_ci DEFAULT '',
  `DAT_1_HABILITACAO` datetime DEFAULT NULL,
  `DES_PAGINA` varchar(100) COLLATE utf8_swedish_ci DEFAULT NULL,
  `COD_AGENTE` int(11) DEFAULT '0',
  `COD_STATUS` int(11) DEFAULT '1',
  `DES_OBSERVACAO` mediumtext COLLATE utf8_swedish_ci,
  `DAT_CADASTRO` date DEFAULT NULL,
  `COD_USUARIO` int(11) DEFAULT '0',
  `VAL_VERBA` double DEFAULT '0',
  `VAL_VERBA_COMBUSTIVEL` float DEFAULT '0',
  `DES_TIPO_CONTA` varchar(20) COLLATE utf8_swedish_ci DEFAULT NULL,
  `COD_BANCO` varchar(4) COLLATE utf8_swedish_ci DEFAULT '0000',
  `COD_AGENCIA` varchar(10) COLLATE utf8_swedish_ci DEFAULT '0',
  `NUM_CONTA` varchar(20) COLLATE utf8_swedish_ci DEFAULT '0',
  `NOM_FAVORECIDO` varchar(70) COLLATE utf8_swedish_ci DEFAULT NULL,
  `NUM_CPF_CNPJ_FAVORECIDO` varchar(20) COLLATE utf8_swedish_ci DEFAULT NULL,
  `DES_FORMA_PAGAMENTO` varchar(30) COLLATE utf8_swedish_ci DEFAULT NULL,
  `COD_CENTRO_CUSTO` int(11) DEFAULT '0',
  `DOM_VITIMA_ROUBO` varchar(1) COLLATE utf8_swedish_ci DEFAULT 'N',
  `QTD_VITIMA_ROUBO` int(11) DEFAULT '0',
  `DOM_ACIDENTES` varchar(1) COLLATE utf8_swedish_ci DEFAULT 'N',
  `QTD_ACIDENTES` int(11) DEFAULT '0',
  `DOM_TRANSPORTE_EMPRESA` varchar(1) COLLATE utf8_swedish_ci DEFAULT 'N',
  `QTD_TRANSPORTE` int(11) DEFAULT '0',
  `DOM_GV` varchar(1) COLLATE utf8_swedish_ci DEFAULT 'N',
  `DAT_GV` date DEFAULT NULL,
  `NOM_EXECUTANTE` varchar(30) COLLATE utf8_swedish_ci DEFAULT 'SISTEMA',
  `DAT_ALTERACAO` datetime DEFAULT NULL,
  PRIMARY KEY (`COD_CADASTRO`),
  KEY `TBENTREGADORES_IDX1` (`DES_RAZAO_SOCIAL`),
  KEY `TBENTREGADORES_IDX2` (`NOM_FANTASIA`),
  KEY `TBENTREGADORES_IDX3` (`NUM_CNPJ`),
  KEY `TBENTREGADORES_IDX4` (`COD_CENTRO_CUSTO`),
  KEY `TBENTREGADORES_IDX0` (`COD_ENTREGADOR`)
) ENGINE=InnoDB AUTO_INCREMENT=99992 DEFAULT CHARSET=utf8 COLLATE=utf8_swedish_ci;
