INSERT INTO rjsmart.tbrelatoriodiario
(DAT_RELATORIO,
DES_PLACA,
NOM_MOTORISTA,
HOR_SAIDA_ORIGEM,
HOR_CHEGADA_FRANQUIA,
HOR_SAIDA_FRANQUIA,
QTD_EXPEDIDORES,
QTD_PESO_DIVERGENCIA,
QTD_AVARIAS_DIVERGENCIA,
DES_OBSERVACOES,
NOM_USUARIO,
DAT_REGISTRO) 
SELECT 
STR_TO_DATE(F1,'%d/%m/%Y') ,
F2,
F3,
CONVERT(F4,TIME),
CONVERT(F5,TIME),
CONVERT(F6,TIME),
CONVERT(F7,SIGNED),
0,
0,
F10, 
'SISTEMA', 
NOW()
FROM rjsmart.planilha_agosto__julho
;
