CREATE TABLE `TBLACRES` (
  `COD_BASE` int(11) NOT NULL,
  `NUM_LACRE` varchar(11) NOT NULL,
  `COD_STATUS` int(11) DEFAULT '0',
  `NOM_USUARIO` varchar(20) DEFAULT 'SISTEMA',
  `DAT_MANUTENCAO` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`COD_BASE`,`NUM_LACRE`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
