CREATE TABLE `TBUSUARIOSAGENTES` (
  `ID_USUARIO_AGENTE` int(11) NOT NULL AUTO_INCREMENT,
  `COD_USUARIO` int(11) DEFAULT NULL,
  `COD_AGENTE` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID_USUARIO_AGENTE`),
  KEY `TB_USUARIOS_AGENTES_IX1` (`COD_USUARIO`),
  KEY `TB_USUARIOS_AGENTES_IX2` (`COD_AGENTE`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
